### ISSUE TITLE
Dependabot PR's dont run `postinstall` script

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#218]
Dependabot auto versions update is cool, but it doesn't run `postinstall` script, which generates the package versions manifest for the plugin to use.

Will need to add another action to do this:

```
on:
  push:
    branches:
      - dependabot/npm_and_yarn/**
  pull_request:
    branches:
      - dependabot/npm_and_yarn/**

... do `pnpm install` and `commit` here
```
